/*CREACIÓN TABLAS TEMPORALES*/
CREATE OR REPLACE TEMP TABLE RUNNER_ORDERS_SILVER AS 
SELECT 
    ORDER_ID,
    RUNNER_ID,
    CASE
        WHEN TRIM(PICKUP_TIME) IN ('null') THEN NULL
        ELSE PICKUP_TIME
    END AS PICKUP_TIME,
    CASE
        WHEN TRIM(DISTANCE) IN ('null') THEN NULL
        ELSE REPLACE(RUNNER_ORDERS.DISTANCE,'km','')
        END AS DISTANCIA_KM,
    CASE
        WHEN TRIM(DURATION) IN ('null') THEN NULL
        ELSE SUBSTR(DURATION, 0, 2)
        END AS DURACION_MINUTOS,
    CASE
        WHEN TRIM(CANCELLATION) IN ('null','') THEN NULL
        ELSE CANCELLATION
    END AS CANCELLATION
FROM RUNNER_ORDERS;

/*CONSULTA DÍA 2*/
SELECT RUNNERS.RUNNER_ID,
    CASE WHEN (SUM(DISTANCIA_KM)) IS NULL
    THEN 0 ELSE (SUM(DISTANCIA_KM))
    END AS DISTANCIA_KM,
    CASE WHEN (ROUND (AVG(DISTANCIA_KM/(DURACION_MINUTOS/60)),2)) IS NULL
    THEN 0 ELSE (ROUND (AVG(DISTANCIA_KM/(DURACION_MINUTOS/60)),2))
    END AS "KM/H"
FROM RUNNER_ORDERS_SILVER
RIGHT JOIN RUNNERS
ON RUNNER_ORDERS_SILVER.RUNNER_ID = RUNNERS.RUNNER_ID
GROUP BY RUNNERS.RUNNER_ID