SELECT RUNNERS.RUNNER_ID,
    CASE WHEN (SUM(DISTANCIA_KM)) IS NULL
    THEN 0 ELSE (SUM(DISTANCIA_KM))
    END AS DISTANCIA_KM,
    CASE WHEN (ROUND (AVG(DISTANCIA_KM/(DURACION_MINUTOS/60)),2)) IS NULL
    THEN 0 ELSE (ROUND (AVG(DISTANCIA_KM/(DURACION_MINUTOS/60)),2))
    END AS "KM/H"
FROM RUNNER_ORDERS_SILVER
RIGHT JOIN RUNNERS
ON RUNNER_ORDERS_SILVER.RUNNER_ID = RUNNERS.RUNNER_ID
GROUP BY RUNNERS.RUNNER_ID