SELECT DISTINCT A.CUSTOMER_ID, B.PRODUCT_NAME
FROM (
    SELECT 
        CUSTOMER_ID,
        PRODUCT_ID,
        RANK() OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE) AS rank_num
    FROM SQL_EN_LLAMAS.CASE01.SALES
) A
INNER JOIN SQL_EN_LLAMAS.CASE01.MENU B ON (A.PRODUCT_ID=B.PRODUCT_ID)
WHERE rank_num = 1;