/*¿EN CUÁNTOS DÍAS DE MEDIA SE REASIGNAN LOS CLIENTES A UN NODO DIFERENTE*/

CREATE OR REPLACE DATABASE SQL_EN_LLAMAS_FNM CLONE SQL_EN_LLAMAS;

CREATE SCHEMA SQL_EN_LLAMAS_FNM.CASE03 CLONE SQL_EN_LLAMAS.CASE03;

USE SCHEMA SQL_EN_LLAMAS_FNM.CASE03;

CREATE OR REPLACE TEMP TABLE CUSTOMER_NODES_SILVER
AS
SELECT CUSTOMER_ID,
    NODE_ID,
    START_DATE,
    LEAD(START_DATE) OVER (PARTITION BY CUSTOMER_ID ORDER BY START_DATE) AS START_DATE_DEF,
    LEAD (NODE_ID) OVER (PARTITION BY CUSTOMER_ID ORDER BY START_DATE) AS NODE_ID_DEF
FROM CUSTOMER_NODES;

SELECT ROUND(AVG(A.NODE_DAYS),1) AS AVG_NODE_DAYS
FROM(
SELECT CUSTOMER_ID,
    NODE_ID,
    NODE_ID_DEF,
    (START_DATE_DEF-START_DATE) AS NODE_DAYS
FROM CUSTOMER_NODES_SILVER
)A
