/*SEMANA 3 - DÍA 3*/
/*CREA UN PROCEDIMIENTO ALMACENADO QUE AL INTRODUCIR EL IDENTIFICADOR DEL CLIENTE Y EL MES,
CALCULE EL TOTAL DE COMPRAS (PURCHASE) Y QUE TE DEVUELVA EL SIGUIENTE MENSAJE:
"EL CLIENTE 1 SE HA GASTADO UN TOTAL DE 1276 EUR EN COMPRAS DE PRODUCTOS EN EL MES DE MARZO"*/

CREATE OR REPLACE PROCEDURE SQL_EN_LLAMAS.CASE03.GASTO_COMPRAS_FNM(CLIENTE INT, MES VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS
DECLARE
    GASTO_CLIENTE INT;
BEGIN
SELECT GASTO_CLIENTE
    INTO GASTO_CLIENTE
    FROM
  (
    SELECT CUSTOMER_ID AS CLIENTE,
     MONTHNAME(TXN_DATE) AS MES,
     SUM(TXN_AMOUNT) AS GASTO_CLIENTE
    FROM CUSTOMER_TRANSACTIONS
    WHERE TXN_TYPE ='purchase'
    GROUP BY CLIENTE, MES
    ORDER BY CLIENTE ASC
    )A
        WHERE CLIENTE = :CLIENTE AND MES = :MES;

    RETURN 'The customer ' ||:CLIENTE||' spent a total of ' ||:GASTO_CLIENTE|| ' EUR in purchases in ' ||:MES||'.';

END;

/*EJEMPLO PARA COMPROBAR QUE EFECTIVAMENTE DEVUELVE LO CORRESPONDIENTE
INTRODUCIMOS EL ID DE CLIENTE Y EL MES ABREVIADO (Jan, Feb, Mar...)*/
CALL SQL_EN_LLAMAS.CASE03.GASTO_COMPRAS_FNM(5,'Mar')
