/*SEMANA 3 - DÍA 4*/

CREATE OR REPLACE PROCEDURE SQL_EN_LLAMAS.CASE03.CALCULO_FNM(CALCULO VARCHAR, CLIENTE INT, MES VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
DECLARE
    TOTAL_COMPRAS INT;
    TOTAL_DEPOSITADO INT;
    TOTAL_RETIRADO INT;
    BALANCE INT;
BEGIN
    SELECT TOTAL_COMPRAS
    INTO TOTAL_COMPRAS
    FROM (
    SELECT CUSTOMER_ID AS CLIENTE,
     MONTHNAME(TXN_DATE) AS MES,
     SUM(TXN_AMOUNT) AS TOTAL_COMPRAS
    FROM CUSTOMER_TRANSACTIONS
    WHERE TXN_TYPE ='purchase'
    GROUP BY CLIENTE, MES
    ORDER BY CLIENTE ASC
    )A
        WHERE CLIENTE = :CLIENTE AND MES = :MES;
        
    SELECT TOTAL_DEPOSITADO
    INTO TOTAL_DEPOSITADO
    FROM (
    SELECT CUSTOMER_ID AS CLIENTE,
     MONTHNAME(TXN_DATE) AS MES,
     SUM(TXN_AMOUNT) AS TOTAL_DEPOSITADO
    FROM CUSTOMER_TRANSACTIONS
    WHERE TXN_TYPE ='deposit'
    GROUP BY CLIENTE, MES
    ORDER BY CLIENTE ASC
    )A
        WHERE CLIENTE = :CLIENTE AND MES = :MES;

    SELECT TOTAL_RETIRADO
    INTO TOTAL_RETIRADO
    FROM (
    SELECT CUSTOMER_ID AS CLIENTE,
     MONTHNAME(TXN_DATE) AS MES,
     SUM(TXN_AMOUNT) AS TOTAL_RETIRADO
    FROM CUSTOMER_TRANSACTIONS
    WHERE TXN_TYPE ='withdrawal'
    GROUP BY CLIENTE, MES
    ORDER BY CLIENTE ASC
    )A
        WHERE CLIENTE = :CLIENTE AND MES = :MES;

BALANCE:=(TOTAL_DEPOSITADO - TOTAL_COMPRAS - TOTAL_RETIRADO);
        
CASE WHEN CALCULO='BALANCE' THEN RETURN 'The balance of the client ' ||:CLIENTE||' is ' ||:BALANCE|| ' EUR in ' ||:MES||'.';
    WHEN CALCULO='TOTAL_COMPRAS' THEN RETURN 'The total spent in purchases of the client ' ||:CLIENTE||' is ' ||:TOTAL_COMPRAS|| ' EUR in ' ||:MES||'.';
    WHEN CALCULO='TOTAL_DEPOSITADO' THEN RETURN 'The total spent in deposits of the client ' ||:CLIENTE||' is ' ||:TOTAL_DEPOSITADO|| ' EUR in ' ||:MES||'.';
    WHEN CALCULO='TOTAL_RETIRADO' THEN RETURN 'The total spent in withdrawals of the client ' ||:CLIENTE||' is ' ||:TOTAL_RETIRADO|| ' EUR in ' ||:MES||'.';
    ELSE RETURN 'The operation identifier is not valid.';
    END CASE;

END;

CALL CALCULO_FNM ('BALANCE',5,'Mar');
CALL CALCULO_FNM ('TOTAL_COMPRAS',5,'Mar');
CALL CALCULO_FNM ('TOTAL_DEPOSITADO',5,'Mar');
CALL CALCULO_FNM ('TOTAL_RETIRADO',5,'Mar');



/*********************************************************/
/***************** COMENTARIO MARÍA *********************/
/*********************************************************/
/* 

PERFECTO Fran!!! Muy bien salvado el ejercicio!

Legibilidad: Yo hubiera tabulado algo más las subconsultas, y los RETUURN de los CASE WHEN del final, me resulta más sencillo de leer. 



*/
