SELECT C.CUSTOMER_ID, SUM(NVL(PRICE,0)) AS GASTO_TOTAL  
FROM SQL_EN_LLAMAS.CASE01.MEMBERS C
LEFT JOIN SQL_EN_LLAMAS.CASE01.SALES A ON (C.CUSTOMER_ID=A.CUSTOMER_ID)
LEFT JOIN SQL_EN_LLAMAS.CASE01.MENU B ON (A.PRODUCT_ID = B.PRODUCT_ID)
GROUP BY C.CUSTOMER_ID;