SELECT DISTINCT A.customer_id CLIENTE,
A.order_date FECHA,
B.product_name PRODUCTO
FROM SQL_EN_LLAMAS.CASE01.SALES A
JOIN SQL_EN_LLAMAS.CASE01.MENU B
ON A.PRODUCT_ID=B.PRODUCT_ID
WHERE order_date=(SELECT MIN(order_date)
FROM SQL_EN_LLAMAS.CASE01.SALES)
