SELECT MEMBERS.CUSTOMER_ID AS "CLIENTE", CASE WHEN SUM(MENU.PRICE) IS NULL THEN 0 ELSE SUM(MENU.PRICE) END AS "GASTO"
FROM SALES
JOIN MENU
ON SALES.PRODUCT_ID = MENU.PRODUCT_ID
FULL JOIN MEMBERS
ON SALES.CUSTOMER_ID = MEMBERS.CUSTOMER_ID
GROUP BY MEMBERS.CUSTOMER_ID
