SELECT MEMBERS.CUSTOMER_ID AS "CLIENTE",  MENU.PRODUCT_NAME AS "PRODUCTO", SALES.ORDER_DATE AS "FECHA PRIMER PEDIDO"
FROM SALES
FULL JOIN MEMBERS
ON SALES.CUSTOMER_ID = MEMBERS.CUSTOMER_ID
JOIN MENU
ON SALES.PRODUCT_ID = MENU.PRODUCT_ID
WHERE ORDER_DATE=(SELECT MIN (ORDER_DATE) FROM SALES)
GROUP BY MEMBERS.CUSTOMER_ID, MENU.PRODUCT_NAME, SALES.ORDER_DATE