SELECT A.CUSTOMER_ID, C.PRODUCT_NAME
FROM SQL_EN_LLAMAS.CASE01.SALES A
INNER JOIN SQL_EN_LLAMAS.CASE01.MEMBERS B
ON A.CUSTOMER_ID = B.CUSTOMER_ID
AND A.ORDER_DATE = B.JOIN_DATE
INNER JOIN SQL_EN_LLAMAS.CASE01.MENU C
ON A.PRODUCT_ID = C.PRODUCT_ID
GROUP BY A.CUSTOMER_ID, C.PRODUCT_NAME;
