SELECT A.CUSTOMER_ID
    ,IFNULL(SUM(C.PRICE),0) AS GASTO
FROM SQL_EN_LLAMAS.CASE01.MEMBERS A
LEFT JOIN SQL_EN_LLAMAS.CASE01.SALES B
ON A.CUSTOMER_ID = B.CUSTOMER_ID
LEFT JOIN SQL_EN_LLAMAS.CASE01.MENU C
ON B.PRODUCT_ID = C.PRODUCT_ID
GROUP BY A.CUSTOMER_ID;
