SELECT A.CUSTOMER_ID, COUNT(DISTINCT B.ORDER_DATE) AS NUM_DIAS_VISITA
FROM SQL_EN_LLAMAS.CASE01.MEMBERS A
LEFT JOIN SQL_EN_LLAMAS.CASE01.SALES B
ON A.CUSTOMER_ID = B.CUSTOMER_ID
GROUP BY A.CUSTOMER_ID;
