SELECT A.CUSTOMER_ID, 
    CASE WHEN C.PRODUCT_NAME IS NULL THEN 'DESCONOCIDO'
        ELSE C.PRODUCT_NAME END AS PRODUCT_NAME 
FROM SQL_EN_LLAMAS.CASE01.MEMBERS A
LEFT JOIN SQL_EN_LLAMAS.CASE01.SALES B
ON A.CUSTOMER_ID = B.CUSTOMER_ID
AND A.JOIN_DATE = B.ORDER_DATE
LEFT JOIN SQL_EN_LLAMAS.CASE01.MENU C
ON B.PRODUCT_ID = C.PRODUCT_ID
GROUP BY A.CUSTOMER_ID, C.PRODUCT_NAME;
