SELECT TOP 1 B.PRODUCT_NAME, COUNT(A.PRODUCT_ID) AS CONTEO 
FROM SQL_EN_LLAMAS.CASE01.SALES A
INNER JOIN SQL_EN_LLAMAS.CASE01.MENU B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY B.PRODUCT_NAME
ORDER BY CONTEO DESC;
