-- ¿Cuál es el primer producto que ha pedido cada cliente? -- 
SELECT 
     A.CLIENTE
    ,LISTAGG(DISTINCT A.PRODUCTO, ', ') AS LISTA_PRODUCTOS
FROM(
    SELECT 
         MEMBERS.CUSTOMER_ID AS CLIENTE
        ,MENU.PRODUCT_NAME AS PRODUCTO
    FROM CASE01.SALES
    FULL JOIN CASE01.MEMBERS
           ON SALES.CUSTOMER_ID = MEMBERS.CUSTOMER_ID
    INNER JOIN CASE01.MENU
           ON SALES.PRODUCT_ID = MENU.PRODUCT_ID
    WHERE (SALES.ORDER_DATE) IN (SELECT MIN(ORDER_DATE)
                                   FROM CASE01.SALES
                                 GROUP BY SALES.CUSTOMER_ID)
    GROUP BY MEMBERS.CUSTOMER_ID, MENU.PRODUCT_NAME)A
GROUP BY A.CLIENTE
ORDER BY A.CLIENTE;
