--TABLAS DE ESTUDIO
--select * from sales
--select * from members
--select * from menu

--CONSIDERACIONES PREVIAS
--TABLA HECHOS SALES S
--TABLA DIMENSIONES MENU M
--TABLA DIMENSIONES MEMBERS MEM

-- PRIMER PRODUCTO QUE COMPRÓ CADA UNO
-- LO MISMO HAY UNA FORMA MAS ELEGANTE, PERO A MI SE ME OCURRE ESTO:
-- DE LA LÍNEA 14 A LA 27 UN INNER JOIN, QUE ASEGURA QUE EL ORDER_DATE COINCIDA CON LA MÍNIMA FECHA
SELECT distinct
S1.CUSTOMER_ID
,M.PRODUCT_NAME        --RESCATO EL PRODUCT NAME DESCRIPTIVO
,S1.ORDER_DATE
FROM SALES S1

INNER JOIN
(
select PRODUCT_ID
       ,min(ORDER_DATE) as MinFecha
       ,max(ORDER_DATE) as MaxFecha
       from SALES 
       group by PRODUCT_ID 
) S2 ON S1.ORDER_DATE=S2.MinFecha         -- AQUÍ NOS ASEGURAMOS LA PRIMERA FECHA

-- UNA VEZ TENEMOS LA MÍNIMA FECHA DE CADA PRODCUTO, RESCATO EL DESCRIPTIVO CON UN LEFT JOIN


LEFT JOIN MENU M
ON M.PRODUCT_ID=S1.PRODUCT_ID

-- MOLA PPORQUE SUSHI Y CURRY PARA EL CUSTOMER ID=A  SE REPITEN YA QUE SE COMPRA EL MISMO DÍA Y LO SACA
