USE SQL_EN_LLAMAS;
USE SCHEMA CASE01;

SELECT M.CUSTOMER_ID, IFNULL(SUM(MEN.PRICE),0) AS TOTAL_SPEND 
    FROM MEMBERS M
    LEFT JOIN SALES S
        ON M.CUSTOMER_ID = S.CUSTOMER_ID
    LEFT JOIN MENU MEN
        ON S.PRODUCT_ID = MEN.PRODUCT_ID
    GROUP BY M.CUSTOMER_ID;
	