USE SQL_EN_LLAMAS;
USE SCHEMA CASE01;

SELECT CUSTOMER_ID, ARRAY_AGG(IFNULL(PRODUCT_NAME,'NO FIRST ORDER')) AS FIRST_ORDER
FROM (
    SELECT M.CUSTOMER_ID, MEN.PRODUCT_NAME, MIN(S.ORDER_DATE) AS FIRST_ORDER_DATE
    FROM MEMBERS M
    LEFT JOIN SALES S
        ON M.CUSTOMER_ID = S.CUSTOMER_ID
    LEFT JOIN MENU MEN
        ON S.PRODUCT_ID = MEN.PRODUCT_ID
    GROUP BY M.CUSTOMER_ID, MEN.PRODUCT_NAME
)
GROUP BY CUSTOMER_ID ORDER BY CUSTOMER_ID;
