USE SQL_EN_LLAMAS;
USE SCHEMA CASE01;

SELECT M.CUSTOMER_ID, COUNT(DISTINCT S.ORDER_DATE) AS NUM_VISITS 
    FROM MEMBERS M 
    LEFT JOIN SALES S
        ON M.CUSTOMER_ID = S.CUSTOMER_ID
    GROUP BY M.CUSTOMER_ID;
