SELECT
    C.CUSTOMER_ID,
    CASE
        WHEN SUM(PRICE)|| '€' IS NULL THEN 0|| '€'
         ELSE SUM(PRICE)|| '€'
    END AS GASTO_POR_CLIENTE
FROM SALES A
LEFT JOIN MENU B
    ON A.PRODUCT_ID = B.PRODUCT_ID
FULL JOIN MEMBERS C
    ON C.CUSTOMER_ID = A.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID;
