SELECT S.CUSTOMER_ID AS CLIENTE,
        SUM(M.PRICE) AS GASTO_TOTAL
FROM SQL_EN_LLAMAS.CASE01.SALES AS S
JOIN SQL_EN_LLAMAS.CASE01.MENU AS M
ON S.PRODUCT_ID = M.PRODUCT_ID
GROUP BY S.CUSTOMER_ID
ORDER BY GASTO_TOTAL DESC
