-- DAY 3 --
/* CREA UNA UNICA CONSULTA SQL PARA REPLICAR LA TABLA
PRODUCT_DETAILS, HAY QUE TRANSFORMAR LOS CONJUNTOS DE DATOS
PRODUCT_HIERARCHY Y PRODUCT_PRICES*/

USE SCHEMA SQL_EN_LLAMAS.CASE04;

CREATE OR REPLACE TEMPORARY TABLE ESPECIALIDAD_SQL_BRONZE_DB_MRA.RETO.PRODUCT_DETAILS_REPLICA_WEEK4
AS
(
    SELECT 
        A.PRODUCT_ID
       ,A.PRICE
       ,B.STYLE_NAME||' '||C.SEGMENT_NAME||' - '||D.CATEGORY_NAME AS PRODUCT_NAME
       ,D.CATEGORY_ID 
       ,C.SEGMENT_ID
       ,B.STYLE_ID
       ,D.CATEGORY_NAME
       ,C.SEGMENT_NAME
       ,B.STYLE_NAME
    FROM PRODUCT_PRICES A
    LEFT JOIN (SELECT
                    DISTINCT ID AS STYLE_ID
                   ,LEVEL_TEXT AS STYLE_NAME
                   ,PARENT_ID
               FROM PRODUCT_HIERARCHY
               WHERE LEVEL_NAME = 'Style')B
           ON A.ID=B.STYLE_ID
    LEFT JOIN (SELECT
                    DISTINCT ID AS SEGMENT_ID
                   ,LEVEL_TEXT AS SEGMENT_NAME
                   ,PARENT_ID
               FROM PRODUCT_HIERARCHY
               WHERE LEVEL_NAME = 'Segment')C
           ON B.PARENT_ID=C.SEGMENT_ID
    
    LEFT JOIN (SELECT
                    DISTINCT ID AS CATEGORY_ID
                   ,LEVEL_TEXT AS CATEGORY_NAME
                   ,PARENT_ID
               FROM PRODUCT_HIERARCHY
               WHERE LEVEL_NAME = 'Category')D
           ON C.PARENT_ID=D.CATEGORY_ID
);

SELECT * FROM ESPECIALIDAD_SQL_BRONZE_DB_MRA.RETO.PRODUCT_DETAILS_REPLICA_WEEK4;



    /*COMENTARIOS JUANPE: TODO CORRECTO*/

