--DAY 5--
/*CREA UNA FUNCION QUE INTRODUCIENDOLE UNA CATEGORIA Y SEGMENTO
MUESTRE EL PRODUCTO MAS VENDIDO DE CADA CATEGORIA Y SEGMENTO*/


CREATE OR REPLACE FUNCTION ESPECIALIDAD_SQL_BRONZE_DB_MRA.RETO.MRA_PRODUCTO_MAS_VENDIDO_CAT_SEG(categoria VARCHAR, segmento VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS 'SELECT
         ''El producto más vendido para la categoría '' || categoria || '' y el segmento '' || segmento || '' es '' || PRODUCT_NAME || ''.''
    FROM (
            SELECT
                S.PROD_ID
               ,COUNT(S.PROD_ID) AS VENDIDOS
               ,PD.PRODUCT_NAME
               ,PD.CATEGORY_ID
               ,PD.CATEGORY_NAME
               ,PD.SEGMENT_ID
               ,PD.SEGMENT_NAME
               ,RANK() OVER(ORDER BY VENDIDOS DESC) AS RANKING_PRODUCTOS
            FROM SQL_EN_LLAMAS.CASE04.SALES S
            INNER JOIN SQL_EN_LLAMAS.CASE04.PRODUCT_DETAILS PD
                   ON S.PROD_ID = PD.PRODUCT_ID
                  AND UPPER(TRIM(CATEGORY_NAME)) = UPPER(TRIM(categoria))
                  AND UPPER(TRIM(SEGMENT_NAME)) = UPPER(TRIM(segmento))
            GROUP BY 1,3,4,5,6,7)A
    WHERE RANKING_PRODUCTOS = 1';


SELECT ESPECIALIDAD_SQL_BRONZE_DB_MRA.RETO.MRA_PRODUCTO_MAS_VENDIDO_CAT_SEG('MENS','SOCKS');
