/*Qué combinacion de productos diferentes aparece en más transacciones (combinación >= 3 productos)*/
                            
WITH DATA AS ( --ELIMINAR DUPLICADOS Y OBETENER NOMBRE DE PRODUCTOS
SELECT 
    A.PROD_ID, A.TXN_ID, B.PRODUCT_NAME
FROM   
   (SELECT DISTINCT PROD_ID, QTY, PRICE, DISCOUNT, MEMBER, TXN_ID, START_TXN_TIME
   FROM CASE04.SALES ) A
LEFT JOIN 
    (SELECT DISTINCT PRODUCT_ID, PRODUCT_NAME 
    FROM CASE04.PRODUCT_DETAILS ) B
  ON A.PROD_ID = B.PRODUCT_ID
), TXN_ID_List AS (
    SELECT DISTINCT TXN_ID 
    FROM CASE04.SALES
)

,PRODUCTOS_BY_TRANSACCION AS (
    SELECT 
		TXN_ID, 
		COUNT(DISTINCT PROD_ID) AS DISTINCT_PRODUCTS
    FROM DATA
    GROUP BY 1 
    HAVING COUNT(DISTINCT PROD_ID) > 2
),
PRODUCT_COMBINED AS (
	SELECT 
		TXN_ID, 
		ARRAY_AGG(PRODUCT_NAME) WITHIN GROUP (ORDER BY PROD_ID) AS PRODUCT_MIX
	FROM DATA
	GROUP BY 1
)

SELECT  ARRAY_TO_STRING(PRODUCT_MIX, ', ') AS PRODUCT_MIX
        ,NUM_TRANSACTIONS
FROM (
    SELECT 
        PRODUCT_MIX
        ,COUNT(A.TXN_ID) AS NUM_TRANSACTIONS
        ,RANK() OVER(ORDER BY NUM_TRANSACTIONS DESC) AS RANK_PRODUCT_LIST
    FROM PRODUCT_COMBINED A 
    INNER JOIN PRODUCTOS_BY_TRANSACCION B
        ON (A.TXN_ID = B.TXN_ID)
    GROUP BY 1
    ORDER BY 2 DESC
    ) AS A
WHERE RANK_PRODUCT_LIST = 1 ;

 

   