SELECT SALES.CUSTOMER_ID AS CLIENTE,
       SALES.ORDER_DATE AS FECHA_PEDIDO,
       MENU.PRODUCT_NAME AS PRODUCTO
FROM SQL_EN_LLAMAS.CASE01.SALES AS SALES
JOIN 
    (SELECT CUSTOMER_ID AS CLIENTE, MIN(ORDER_DATE) AS MIN_FECHA
     FROM SQL_EN_LLAMAS.CASE01.SALES
     GROUP BY CUSTOMER_ID
    ) AS MIN_DATE
ON SALES.ORDER_DATE = MIN_DATE.MIN_FECHA
JOIN SQL_EN_LLAMAS.CASE01.MENU AS MENU
ON SALES.PRODUCT_ID = MENU.PRODUCT_ID
GROUP BY SALES.CUSTOMER_ID, SALES.ORDER_DATE, MENU.PRODUCT_NAME
ORDER BY CLIENTE
