//** ¿Qué es mejor? Así **//

SELECT MB.CUSTOMER_ID AS CLIENTE, ZEROIFNULL(SUM(P.PUNTOS)) AS PUNTOS
FROM (
    SELECT S.CUSTOMER_ID AS CLIENTE,
          CASE WHEN M.PRODUCT_NAME = 'sushi' THEN 20
            ELSE 10
          END AS PUNTOS
    FROM SQL_EN_LLAMAS.CASE01.SALES AS S
    LEFT JOIN SQL_EN_LLAMAS.CASE01.MENU AS M
    ON S.PRODUCT_ID = M.PRODUCT_ID
    ) AS P
RIGHT JOIN SQL_EN_LLAMAS.CASE01.MEMBERS AS MB
ON P.CLIENTE = MB.CUSTOMER_ID
GROUP BY MB.CUSTOMER_ID


//** ¿o con el SUM en la Subslect? **//

SELECT MB.CUSTOMER_ID AS CLIENTE, ZEROIFNULL(P.PUNTOS) AS PUNTOS
FROM (
    SELECT S.CUSTOMER_ID AS CLIENTE,
           SUM (CASE WHEN M.PRODUCT_NAME = 'sushi'
                THEN 20
                ELSE 10
            END) AS PUNTOS
    FROM SQL_EN_LLAMAS.CASE01.SALES AS S
    LEFT JOIN SQL_EN_LLAMAS.CASE01.MENU AS M
    ON S.PRODUCT_ID = M.PRODUCT_ID
    GROUP BY S.CUSTOMER_ID
    ) AS P
RIGHT JOIN SQL_EN_LLAMAS.CASE01.MEMBERS AS MB
ON P.CLIENTE = MB.CUSTOMER_ID
