SELECT MB.CUSTOMER_ID AS CLIENTE,
        COUNT(DISTINCT S.ORDER_DATE) AS DIAS_VISITADOS
FROM SQL_EN_LLAMAS.CASE01.MEMBERS AS MB
LEFT JOIN SQL_EN_LLAMAS.CASE01.SALES AS S
ON MB.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY MB.CUSTOMER_ID
ORDER BY CLIENTE
