SELECT M.PRODUCT_NAME AS PRODUCTO,
        COUNT(S.PRODUCT_ID) AS VECES_PEDIDO
FROM SQL_EN_LLAMAS.CASE01.SALES AS S
RIGHT JOIN SQL_EN_LLAMAS.CASE01.MENU AS M
ON M.PRODUCT_ID = S.PRODUCT_ID
GROUP BY M.PRODUCT_NAME
ORDER BY VECES_PEDIDO DESC
LIMIT 1
