--¿EN CUÁNTOS DÍAS DE MEDIA SE REASIGNAN LOS CLIENTES A UN NODO DIFERENTE?--

WITH NODOS_CLIENTE AS
(
    SELECT
         CUSTOMER_ID
        ,REGION_ID
        ,NODE_ID
        ,START_DATE
        ,END_DATE
        ,NVL(LAG(NODE_ID) OVER (PARTITION BY CUSTOMER_ID ORDER BY END_DATE),-1) AS NODO_ANTERIOR
        ,NVL(LEAD(NODE_ID) OVER (PARTITION BY CUSTOMER_ID ORDER BY END_DATE), -1) AS NODO_SIGUIENTE
    FROM 
        SQL_EN_LLAMAS.CASE03.CUSTOMER_NODES
    WHERE 
        END_DATE <> TO_DATE('9999-12-31')
),
CLEANED_NODES AS
(
    SELECT 
         A.*
    FROM NODOS_CLIENTE A
    WHERE NOT (NODE_ID = NODO_SIGUIENTE  AND NODO_ANTERIOR = NODE_ID)
    ORDER BY START_DATE
)

SELECT 
    ROUND(AVG(DATEDIFF(DAY,FECHA_COMIENZO_ACTUALIZADA,FECHA_FINALIZACION_ACTUALIZADA)),2) AS MEDIA_DIAS_CAMBIO_NODO
FROM (
        SELECT
            DISTINCT CUSTOMER_ID
           ,REGION_ID
           ,NODE_ID
           ,CASE
                WHEN NODO_ANTERIOR = NODE_ID THEN LAG(START_DATE) OVER (PARTITION BY CUSTOMER_ID ORDER BY END_DATE)
                WHEN NODO_ANTERIOR <> NODE_ID THEN START_DATE
            END AS FECHA_COMIENZO_ACTUALIZADA
           ,CASE
                WHEN NODO_SIGUIENTE = NODE_ID THEN LEAD(END_DATE) OVER (PARTITION BY CUSTOMER_ID ORDER BY END_DATE)
                WHEN NODO_SIGUIENTE <> NODE_ID THEN END_DATE
            END AS FECHA_FINALIZACION_ACTUALIZADA
        FROM CLEANED_NODES)A;
