
-- PARA CADA MES, ¿CUÁNTOS CLIENTES REALIZAN MAS DE 1 DEPOSITO Y 1 COMPRA O UN 1 RETIRO EN UN SOLO MES
SELECT
    B.MES_TXN AS MES
   ,COUNT(B.CUSTOMER_ID) AS CLIENTES
FROM (
        SELECT
            CUSTOMER_ID
           ,MES_TXN
        FROM (
            SELECT
                CUSTOMER_ID
               ,EXTRACT(MONTH FROM TXN_DATE) AS MES_TXN
               ,SUM(CASE WHEN TXN_TYPE = 'deposit' THEN 1 ELSE 0 END) AS DEPOSITO
               ,SUM(CASE WHEN TXN_TYPE = 'purchase' THEN 1 ELSE 0 END) AS COMPRA
               ,SUM(CASE WHEN TXN_TYPE = 'withdrawal' THEN 1 ELSE 0 END) AS RETIRO
            FROM CUSTOMER_TRANSACTIONS
            GROUP BY 1, 2
        ) A
        WHERE (DEPOSITO > 1 AND COMPRA > 1) OR RETIRO > 1
        GROUP BY 1, 2
) B
GROUP BY 1
ORDER BY 1 ASC;
