-- DAY 3 --

-- CREA UN PROCEDIMIENTO ALMACENADO QUE AL INTRODUCIR EL IDENTIFICADOR DEL CLIENTE
-- Y EL MES, CALCULE EL TOTAL DE COMPRAS (PURCHASE) Y QUE TE DEVUELVE EL SIGUIENTE MENSAJE:
--EL CLIENTE 1 SE HA GASTADO UN TOTAL DE 1276 EUROS EN COMPRAS DE PRODUCTOS EN EL MES DE MARZO

-- ME HE CREADO UNA TABLA TEMPORAL PARA PODER SACAR LOS MESES EN ESPAÑOL
-- SE QUE HAY ESTÁ MONTHNAME PERO NO DEVUELVE EXACTAMENTE EL FORMATO DESEADO.
CREATE OR REPLACE TEMPORARY TABLE ESPECIALIDAD_SQL_BRONZE_DB_MRA.RETO.MESES AS
    SELECT
      1 AS MONTH_NUMBER, 'ENERO' AS MONTH_NAME
    UNION ALL SELECT 2, 'FEBRERO'
    UNION ALL SELECT 3, 'MARZO'
    UNION ALL SELECT 4, 'ABRIL'
    UNION ALL SELECT 5, 'MAYO'
    UNION ALL SELECT 6, 'JUNIO'
    UNION ALL SELECT 7, 'JULIO'
    UNION ALL SELECT 8, 'AGOSTO'
    UNION ALL SELECT 9, 'SEPTIEMBRE'
    UNION ALL SELECT 10, 'OCTUBRE'
    UNION ALL SELECT 11, 'NOVIEMBRE'
    UNION ALL SELECT 12, 'DICIEMBRE';


CREATE OR REPLACE PROCEDURE SQL_EN_LLAMAS.CASE03.MRA_CALCULAR_COMPRAS(id_cliente INTEGER, mes VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS
DECLARE
    GASTO_TOTAL INT;
BEGIN
    SELECT SUM(GASTO_CLIENTE) INTO GASTO_TOTAL
    FROM (
        SELECT 
            CUSTOMER_ID
           ,MONTH(TXN_DATE) AS MES
           ,M.MONTH_NAME
           ,TXN_AMOUNT AS GASTO_CLIENTE
        FROM CUSTOMER_TRANSACTIONS CT
        LEFT JOIN  ESPECIALIDAD_SQL_BRONZE_DB_MRA.RETO.MESES M
               ON MONTH(CT.TXN_DATE) = M.MONTH_NUMBER
        WHERE CUSTOMER_ID = :id_cliente
        AND MONTH_NAME = :mes
    );

    RETURN 'EL CLIENTE ' ||:id_cliente|| ' HA GASTADO UN TOTAL DE ' ||:GASTO_TOTAL|| ' EUR EN COMPRAS DE PRODUCTOS EN EL MES DE ' ||:mes||'.';

END;

-- EJEMPLO PARA EL CLIENTE 1 Y EL MES DE MARZO--
CALL SQL_EN_LLAMAS.CASE03.MRA_CALCULAR_COMPRAS(1, 'MARZO');
