USE SQL_EN_LLAMAS;

SELECT  
        --IDs
        S.CUSTOMER_ID

        --Metricas
        ,SUM(M.PRICE) AS PRICE

FROM CASE01.SALES S
LEFT JOIN CASE01.MENU M
    ON S.PRODUCT_ID = M.PRODUCT_ID
GROUP BY 1;