----------DIA1-------------
WITH PIZZA_MODIFICADAS AS (
SELECT A.RUNNER_ID,
CASE
    WHEN (TRIM(EXCLUSIONS) = 'null' OR EXCLUSIONS IS NULL OR EXCLUSIONS = '')
    AND (TRIM(EXTRAS) = 'null' OR EXTRAS IS NULL  OR EXTRAS = '') THEN 'NO'
    ELSE 'SI'
END AS PIZZA_MOD,
COUNT(*) AS CONT_PIZZA_MOD
FROM RUNNERS A
LEFT JOIN RUNNER_ORDERS R
ON A.RUNNER_ID = R.RUNNER_ID
LEFT JOIN CUSTOMER_ORDERS C
ON C.ORDER_ID = R.ORDER_ID
WHERE PIZZA_MOD = 'SI'
AND PICKUP_TIME <> 'null'
GROUP BY 1,2
),

PIZZAS_ENTREGADAS AS (
SELECT COUNT(CASE WHEN PICKUP_TIME <> 'null' THEN C.PIZZA_ID ELSE NULL END) AS  PIZZA_EXITO,
COUNT(*) AS PIZZAS_PEDIDAS,
R.RUNNER_ID 
FROM CUSTOMER_ORDERS C
LEFT JOIN RUNNER_ORDERS R
ON R.ORDER_ID = C.ORDER_ID
GROUP BY R.RUNNER_ID
),


PEDIDOS_REALIZADOS AS (
SELECT COUNT(CASE WHEN PICKUP_TIME <> 'null' THEN ORDER_ID ELSE NULL END) AS PEDIDOS_EXITO,
COUNT(*) as PEDIDOS_TOTALES,
RUNNER_ID 
FROM RUNNER_ORDERS R
GROUP BY RUNNER_ID
)

SELECT R.RUNNER_ID,
ZEROIFNULL(PEDIDOS_EXITO),
ZEROIFNULL((PEDIDOS_EXITO/PEDIDOS_TOTALES)*100) AS PCT_PEDIDOS_EXITO,
ZEROIFNULL(PIZZA_EXITO),
ZEROIFNULL((CONT_PIZZA_MOD/PIZZA_EXITO)*100) AS PCT_PIZZA_MOD
FROM RUNNERS R
LEFT JOIN PIZZAS_ENTREGADAS P
ON R.RUNNER_ID = P.RUNNER_ID
LEFT JOIN PEDIDOS_REALIZADOS O
ON P.RUNNER_ID = O.RUNNER_ID
LEFT JOIN PIZZA_MODIFICADAS M
ON M.RUNNER_ID = P.RUNNER_ID
ORDER BY RUNNER_ID;
