CREATE TEMPORARY TABLE SQL_EN_LLAMAS.CASE04.DAY3_WEEK_4_MAT AS(
WITH TABLE_CATEGORY AS (
 SELECT DISTINCT ID AS ID_CATEGORY,
        LEVEL_TEXT AS  DESC_CATEGORY
        FROM SQL_EN_LLAMAS.CASE04.PRODUCT_HIERARCHY
        WHERE LEVEL_NAME='Category'
), 
TABLE_SEGMENT AS (
 SELECT DISTINCT ID AS ID_SEGMENT,
        LEVEL_TEXT AS  DESC_SEGMENT,
        PARENT_ID
        FROM SQL_EN_LLAMAS.CASE04.PRODUCT_HIERARCHY
        WHERE LEVEL_NAME='Segment'
), 
TABLE_STYLE AS (
 SELECT DISTINCT ID AS ID_STYLE,
        LEVEL_TEXT AS  DESC_STYLE,
        PARENT_ID
        FROM SQL_EN_LLAMAS.CASE04.PRODUCT_HIERARCHY
        WHERE LEVEL_NAME='Style'
)
SELECT 
    PRODUCT_ID, 
    PRICE,
    (B.DESC_STYLE || ' ' || C.DESC_SEGMENT || ' - ' || D.DESC_CATEGORY) AS PRODUCT_NAME,
    D.ID_CATEGORY AS CATEGORY_ID,
    C.ID_SEGMENT AS SEGMENT_ID,
    B.ID_STYLE AS STYLE_ID,
    D.DESC_CATEGORY AS CATEGORY_NAME,
    C.DESC_SEGMENT AS SEGMENT_NAME,
    B.DESC_STYLE AS STYLE_NAME
FROM SQL_EN_LLAMAS.CASE04.PRODUCT_PRICES A
LEFT JOIN TABLE_STYLE B
    ON (A.ID=B.ID_STYLE)
LEFT JOIN TABLE_SEGMENT C
    ON (B.PARENT_ID=C.ID_SEGMENT)
LEFT JOIN TABLE_CATEGORY D
    ON (C.PARENT_ID=D.ID_CATEGORY)
);

SELECT * FROM SQL_EN_LLAMAS.CASE04.DAY3_WEEK_4_MAT;


    /*COMENTARIOS JUANPE: TODO CORRECTO*/
