WITH PIZZA_INGREDIENTES AS
(
SELECT PIZZA_ID, VALUE::STRING AS PIZZA_TOPPING_ID
    FROM SQL_EN_LLAMAS.CASE02.PIZZA_RECIPES
    , lateral flatten ( input => SPLIT(TOPPINGS, ',')  )
)
SELECT 
    TOPPING_ID, 
    TOPPING_NAME, 
    COUNT(TOPPING_ID) AS CONTEO
FROM SQL_EN_LLAMAS.CASE02.PIZZA_TOPPINGS
LEFT JOIN PIZZA_INGREDIENTES 
    ON (TOPPING_ID=PIZZA_TOPPING_ID)
GROUP BY 1,2
order by 1;