WITH CUSTOMER_ORDERS AS (
    SELECT
        ORDER_ID,
        CASE WHEN PIZZA_ID = 1 THEN 12 ELSE 10 END AS PRECIO,
        CASE WHEN EXTRAS IN ('', 'null') THEN NULL ELSE EXTRAS END AS EXTRAS_CLEANED,
        IFNULL(LENGTH(REPLACE(REPLACE(EXTRAS_CLEANED,',',''),' ','')), 0) AS NUM_TOPPINGS_EXTRA,
        PRECIO + NUM_TOPPINGS_EXTRA AS PRECIO_TOTAL
    FROM SQL_EN_LLAMAS.CASE02.CUSTOMER_ORDERS
),

RUNNER_ORDERS AS (
    SELECT
        ORDER_ID,
        CAST(REPLACE(DISTANCE,'km','') AS NUMBER(5,2)) AS DISTANCE_NUMBER,
        0.3 * DISTANCE_NUMBER AS COSTE_RUNNER_PEDIDO,
        CASE WHEN CANCELLATION IN ('', 'null') THEN NULL ELSE CANCELLATION END AS CANCELLATION_REAL
    FROM SQL_EN_LLAMAS.CASE02.RUNNER_ORDERS
    WHERE CANCELLATION_REAL IS NULL
),

BENEFICIO_LIMPIO_POR_PEDIDO AS (
    SELECT
        CO.ORDER_ID,
        CAST(SUM(CO.PRECIO_TOTAL) AS NUMBER(5,2)) AS GANANCIA_PEDIDO,
        RO.COSTE_RUNNER_PEDIDO,
        CAST((GANANCIA_PEDIDO - RO.COSTE_RUNNER_PEDIDO) AS NUMBER(5,2)) AS BENEFICIO_LIMPIO
    FROM CUSTOMER_ORDERS CO
    INNER JOIN RUNNER_ORDERS RO
    ON CO.ORDER_ID = RO.ORDER_ID
    GROUP BY CO.ORDER_ID, RO.COSTE_RUNNER_PEDIDO
)

SELECT SUM(BENEFICIO_LIMPIO) AS BENEFICIO_TOTAL
FROM BENEFICIO_LIMPIO_POR_PEDIDO;
