//**Perdón por el retraso. El trabajo diario no me permite ir al día con los ejercicios**//

WITH RUNNER_ORDERS AS (
    SELECT
        ORDER_ID,
        RUNNER_ID,
        PICKUP_TIME,
        DISTANCE,
        DURATION,
        CASE WHEN CANCELLATION IN ('', 'null') THEN NULL ELSE CANCELLATION END AS CANCELLATION_REAL
    FROM SQL_EN_LLAMAS.CASE02.RUNNER_ORDERS
    WHERE CANCELLATION_REAL IS NULL
),

CUSTOMER_ORDERS AS (
    SELECT
        ORDER_ID,
        CUSTOMER_ID,
        PIZZA_ID,
        ORDER_TIME,
        CASE WHEN EXCLUSIONS IN ('', 'null') THEN NULL ELSE EXCLUSIONS END AS EXCLUSIONS_REAL,
        CASE WHEN EXTRAS IN ('', 'null') THEN NULL ELSE EXTRAS END AS EXTRAS_REAL
    FROM SQL_EN_LLAMAS.CASE02.CUSTOMER_ORDERS
),

PEDIDOS_RUNNER AS (
    SELECT
        RUNNER_ID,
        COUNT(*) AS PEDIDOS_CON_EXITO
    FROM RUNNER_ORDERS
    GROUP BY RUNNER_ID
),

NUMERO_PIZZAS AS (
    SELECT
        RO.RUNNER_ID,
        COUNT(*) AS PIZZAS_CON_EXITO
    FROM RUNNER_ORDERS RO 
    INNER JOIN CUSTOMER_ORDERS CO
        ON RO.ORDER_ID = CO.ORDER_ID
    GROUP BY RO.RUNNER_ID
),

PEDIDOS_TOTALES AS (
    SELECT
        RUNNER_ID,
        COUNT(ORDER_ID) AS TOTAL_PEDIDOS
    FROM SQL_EN_LLAMAS.CASE02.RUNNER_ORDERS
    GROUP BY RUNNER_ID
),

PIZZAS_MODIFICADAS AS (
    SELECT
        RO.RUNNER_ID,
        COUNT(*) AS PIZZAS_MODIFICADAS
    FROM RUNNER_ORDERS RO
    JOIN CUSTOMER_ORDERS CO
        ON RO.ORDER_ID = CO.ORDER_ID
    WHERE CO.EXCLUSIONS_REAL IS NOT NULL OR CO.EXTRAS_REAL IS NOT NULL
    GROUP BY RO.RUNNER_ID
)

SELECT
    PR.RUNNER_ID,
    PR.PEDIDOS_CON_EXITO,
    NP.PIZZAS_CON_EXITO,
    CAST ((PR.PEDIDOS_CON_EXITO/PT.TOTAL_PEDIDOS)*100 AS NUMBER(5,2)) AS "%_PEDIDOS_EXITO",
    CAST((PM.PIZZAS_MODIFICADAS/NP.PIZZAS_CON_EXITO)*100 AS NUMBER(5,2)) AS "%_PIZZAS_MODIFICADAS_EXITO"
FROM PEDIDOS_RUNNER PR
INNER JOIN NUMERO_PIZZAS NP
    ON PR.RUNNER_ID = NP.RUNNER_ID
INNER JOIN PEDIDOS_TOTALES PT
    ON PR.RUNNER_ID = PT.RUNNER_ID
INNER JOIN PIZZAS_MODIFICADAS PM
    ON PR.RUNNER_ID = PM.RUNNER_ID
;
