WITH RUNNER_ORDERS AS (
    SELECT
        ORDER_ID,
        RUNNER_ID,
        PICKUP_TIME,
        CAST(REPLACE(DISTANCE,'km','') AS NUMBER(5,2)) AS DISTANCE_NUMBER,
        CAST(REPLACE(REPLACE(REPLACE(DURATION,'minutes',''),'mins',''),'minute','') AS NUMBER(5,2)) AS DURATION_NUMBER,
        DISTANCE_NUMBER/(DURATION_NUMBER/60) AS KM_H,
        CASE WHEN CANCELLATION IN ('', 'null') THEN NULL ELSE CANCELLATION END AS CANCELLATION_REAL
    FROM SQL_EN_LLAMAS.CASE02.RUNNER_ORDERS
    WHERE CANCELLATION_REAL IS NULL
)

SELECT
    RUNNER_ID,
    SUM(DISTANCE_NUMBER) AS DISTANCE_TOTAL,
    CAST(AVG(KM_H) AS NUMBER(5,2)) AS VELOCIDAD_PROMEDIO
FROM RUNNER_ORDERS
GROUP BY RUNNER_ID;
