SELECT PRODUCT_NAME, 
        VECES 
FROM(
SELECT B.PRODUCT_NAME, 
        ROW_NUMBER () OVER(ORDER BY COUNT(B.PRODUCT_ID) DESC) AS ROW_NUM, 
        COUNT(B.PRODUCT_ID) AS VECES
FROM SQL_EN_LLAMAS.CASE01.SALES A
INNER JOIN SQL_EN_LLAMAS.CASE01.MENU B 
        ON (A.PRODUCT_ID=B.PRODUCT_ID)
GROUP BY B.PRODUCT_NAME)
WHERE ROW_NUM=1;